[package]
name = "yakuzaishi"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "yakuzaishi"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]

# Windows uncomment:
# amethyst = { version = "0.15.0", features = ["vulkan", "tiles", "test-support"]}

# MacOS uncomment:
amethyst = { version = "0.15.0", features = ["metal", "tiles", "test-support"]}

amethyst_test = "0.15"
log = "0.4"
image = "0.25.0"
tiled = "0.11.2"
rand = "0.8.4"
