[package]
name = "yakuzaishi"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "yakuzaishi"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]

# Windows uncomment:
# bevy = { version = "0.13.1"}

# MacOS uncomment:
bevy = { version = "0.13.1" }

log = "0.4"
log4rs = "1.3"
image = "0.25.0"
tiled = "0.11.2"
rand = "0.8.4"
serde = { version = "1.0.197", features = ["derive"] }
