name: Build on macOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-apple-darwin
        profile: minimal
        override: true
    - name: Build with Metal
      run: cargo build --features "amethyst/metal"
